trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: installAndBuild
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm i
      npm run build
    displayName: 'npm install and build'
