trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Install
    jobs:
      - job: InstallNode
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
            displayName: 'npm install'

  - stage: Build
    dependsOn: Install
    jobs:
      - job: BuildReactApp
        steps:
          - script: |
              npm run build
            displayName: 'Build React App'